site_name: Cubex User Interface Tutorial
site_url: https://cubex30.github.io/user-interface-tutorial
repo_url: https://github.com/cubex30/user-interface-tutorial
copyright: Copyright &copy; 2017 Cubex LLC
pages:
    - Home: index.md
    - Overview:
        - Getting Started: 0-Overview/0.0-Getting-Started.md
        - Displaying Data: 0-Overview/0.1-Displaying-Data.md
        - Updating Data: 0-Overview/0.2-Updating-Data.md
        - Computed Properties: 0-Overview/0.3-Computed-Properties.md
        - Handling Events: 0-Overview/0.4-Handling-Events.md
        - Arrays and Hashes: 0-Overview/0.5-Arrays-and-Hashes.md
        - TypeScript: 0-Overview/0.6-TypeScript.md
        - Asynchronous Execution: 0-Overview/0.7-Asynchronous-Execution.md
    - Using Recoil:
        - Installing Recoil: 1-Using-Recoil/1.0-Installing-Recoil.md
        - Using Recoil Docs: 1-Using-Recoil/1.1-Using-Recoil-Docs.md
    - Using Application State:
        - State Organization: 2-Using-Application-State/2.0-State-Organization.md
        - Connections: 2-Using-Application-State/2.1-Connections.md
        - Models and Stores: 2-Using-Application-State/2.2-Models-and-Stores.md
        - Managers: 2-Using-Application-State/2.3-Managers.md
        - Workflows: 2-Using-Application-State/2.4-Workflows.md
        - Routing: 2-Using-Application-State/2.5-Routing.md
theme: readthedocs