site_name: Cubex User Interface Tutorial
site_url: https://cubex30.github.io/user-interface-tutorial
repo_url: https://github.com/cubex30/user-interface-tutorial
copyright: Copyright &copy; 2017 Cubex LLC
pages:
    - Home: index.md
    - Overview:
        - Getting Started: 0-Overview/0.0-Getting-Started.md
        - Displaying Data: 0-Overview/0.1-Displaying-Data.md
        - Updating Data: 0-Overview/0.2-Updating-Data.md
theme: readthedocs